// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZUbfjhUV2-eW3wqVVPy9BxQ1PglNMks4',
    appId: '1:713808140145:web:f009a5f68d1ee3bc5dc8d0',
    messagingSenderId: '713808140145',
    projectId: 'mecreatefirebase',
    authDomain: 'mecreatefirebase.firebaseapp.com',
    storageBucket: 'mecreatefirebase.appspot.com',
    measurementId: 'G-4EDEWXVSRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJFONuiOLhunWieSaaEZp8PRvilfxTQ8A',
    appId: '1:713808140145:android:b27c1dba7d5a2c315dc8d0',
    messagingSenderId: '713808140145',
    projectId: 'mecreatefirebase',
    storageBucket: 'mecreatefirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNlvdrcAvPON4uBhfrVg6bCJl558ZlIxE',
    appId: '1:713808140145:ios:3801b17c70c4d9c45dc8d0',
    messagingSenderId: '713808140145',
    projectId: 'mecreatefirebase',
    storageBucket: 'mecreatefirebase.appspot.com',
    iosBundleId: 'com.example.mecreateFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNlvdrcAvPON4uBhfrVg6bCJl558ZlIxE',
    appId: '1:713808140145:ios:3801b17c70c4d9c45dc8d0',
    messagingSenderId: '713808140145',
    projectId: 'mecreatefirebase',
    storageBucket: 'mecreatefirebase.appspot.com',
    iosBundleId: 'com.example.mecreateFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZUbfjhUV2-eW3wqVVPy9BxQ1PglNMks4',
    appId: '1:713808140145:web:d9cc5e3de2ff137d5dc8d0',
    messagingSenderId: '713808140145',
    projectId: 'mecreatefirebase',
    authDomain: 'mecreatefirebase.firebaseapp.com',
    storageBucket: 'mecreatefirebase.appspot.com',
    measurementId: 'G-V865SNJXXP',
  );
}
